site_name: matthew_freeman(1) - software engineer

site_url:

repo_url: https://github.com/m6freeman/m6freeman.github.io
repo_name: m6freeman.github.io

theme:
  name: terminal
  logo:
  palette: gruvbox_dark
  font:
    code: Consolas
  features:
    - search.suggest    
    - search.highlightgest
    - toc.follow
    - navigation.side.hide
    - navigation.side.indexes
    - navigation.side.toc.show
    - navigation.top.show
    - navigation.top.cursor_animation.show
    - navigation.top.search_button.show
    - revision.date.show
    - revision.history.show
    - style.links.underline.hide

markdown_extensions:
  - toc:
      toc_depth: 2

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/m6freeman
    - icon: fontawesome/brands/linkedin
      link: https://linked.in/m6freeman
